export const REGEX_CONTROL_NUMBER =
  /^[0-9]{2}1(M|D|A|P|G|GD|DD)(C|0|D|E)[0-9]{3}/i;

export const MOTIVATION_TYPES = [
  "Amotivación",
  "Motivación interna",
  "Motivación externa",
];

export const ADVICES = [
  "Establece metas claras y realistas para tus estudios.",
  "Divide tus tareas en pasos más pequeños y alcanzables.",
  "Crea un horario de estudio y respétalo.",
  "Encuentra un lugar de estudio tranquilo y cómodo.",
  "Usa técnicas de estudio como resúmenes y mapas mentales.",
  "Premia tus logros con pequeños incentivos.",
  "Busca inspiración en personas exitosas.",
  "Mantén una actitud positiva hacia tus estudios.",
  "Rodéate de compañeros motivados y positivos.",
  "Visualiza el éxito y cómo te sentirás al lograrlo.",
  "Recuerda por qué comenzaste a estudiar en primer lugar.",
  "Practica la autorreflexión para mejorar constantemente.",
  "Aprende a manejar el estrés y la presión.",
  "Descubre tu estilo de aprendizaje y adáptate a él.",
  "Establece recompensas a largo plazo por tus metas mayores.",
  "Encuentra el equilibrio entre el estudio y el tiempo libre.",
  "Duerme lo suficiente para mantener tu mente alerta.",
  "Convierte el estudio en un hábito diario.",
  "Concéntrate en el progreso, no en la perfección.",
  "Busca la ayuda de un mentor o tutor cuando sea necesario.",
  "Desglosa proyectos grandes en tareas más pequeñas.",
  "Crea un ambiente de estudio inspirador con elementos motivadores.",
  "Establece un sistema de seguimiento para tus avances.",
  "Conoce tus puntos fuertes y utilízalos a tu favor.",
  "Aprende a decir no a distracciones innecesarias.",
  "Explora diferentes recursos educativos para mantenerte interesado.",
  "Celebra tus éxitos, sin importar cuán pequeños sean.",
  "Desarrolla tu capacidad de concentración y atención.",
  "Mantén un diario de tus logros y desafíos.",
  "Evita la comparación con otros estudiantes.",
  "Enfrenta las dificultades como oportunidades de crecimiento.",
  "Busca feedback constructivo para mejorar constantemente.",
  "Utiliza la tecnología de manera inteligente para el estudio.",
  "Establece límites de tiempo para cada tarea y cúmplelos.",
  "Convierte la música en tu aliada durante el estudio.",
  "Aprende a administrar eficazmente tu tiempo.",
  "Haz ejercicios regulares para mantener tu energía.",
  "Busca conexiones entre el material de estudio y tu vida real.",
  "Sé amable contigo mismo, incluso cuando enfrentes desafíos.",
  "Estimula tu creatividad al abordar los problemas de manera única.",
  "Encuentra formas de relacionar el contenido con tus intereses.",
  "Involucra tus sentidos en el proceso de aprendizaje.",
  "Establece límites saludables para el uso de dispositivos electrónicos.",
  "Practica la gratitud para mantener una perspectiva positiva.",
  "Aprende a lidiar con la procrastinación de manera efectiva.",
  "Haz pausas regulares para mantener tu mente fresca.",
  "Busca el apoyo de amigos y familiares en tu viaje educativo.",
  "Abraza los desafíos como oportunidades para aprender.",
  "Crea un ambiente de estudio libre de distracciones.",
  "Establece consecuencias realistas para no cumplir con tus objetivos.",
  "Fomenta la curiosidad y haz preguntas constantemente.",
  "Visualiza el resultado final para mantenerte motivado.",
  "Aprende a adaptarte a los cambios en tus planes de estudio.",
  "Cultiva la perseverancia frente a la adversidad.",
  "Utiliza herramientas en línea para mejorar tus habilidades.",
  "Establece un sistema de recompensas para tus hitos académicos.",
  "Construye una red de apoyo con tus compañeros de clase.",
  "Enfrenta las dificultades con una mentalidad de resolución de problemas.",
  "Explora diferentes enfoques para abordar un mismo tema.",
  "Haz del aprendizaje una experiencia divertida y emocionante.",
  "Establece límites claros entre tu tiempo de estudio y tu tiempo libre.",
  "Utiliza aplicaciones y herramientas de organización.",
  "Crea un mantra personal que te motive en momentos difíciles.",
  "Busca modelos a seguir que hayan alcanzado el éxito académico.",
  "Apunta a la mejora constante en lugar de la perfección instantánea.",
  "Explora nuevas formas de hacer las cosas en tu estudio.",
  "Aprende a aceptar los errores como oportunidades de aprendizaje.",
  "Establece un sistema de apoyo con amigos que compartan tus objetivos.",
  "Encuentra formas de relacionar el contenido con experiencias personales.",
  "Estudia en bloques de tiempo concentrados y luego descansa.",
  "Desafía tus propias creencias sobre tus capacidades académicas.",
  "Establece recordatorios visuales de tus objetivos principales.",
  "Utiliza la música para crear un ambiente de estudio productivo.",
  "Mantén tu espacio de estudio ordenado y organizado.",
  "Aborda las tareas más difíciles cuando tu energía esté en su punto máximo.",
  "Recompénsate después de completar tareas importantes.",
  "Utiliza ejemplos del mundo real para entender conceptos abstractos.",
  "Crea un plan de estudio que se adapte a tu estilo de vida.",
  "Aprovecha al máximo los recursos disponibles en tu institución educativa.",
  "Fomenta la autodisciplina para seguir tu horario de estudio.",
  "Encuentra maneras de aplicar lo que aprendes en situaciones prácticas.",
  "Aprende a priorizar tareas según su importancia y urgencia.",
  "Involucra a tus amigos en sesiones de estudio colaborativas.",
  "Establece metas a corto plazo para mantenerte enfocado.",
  "Busca oportunidades para enseñar lo que has aprendido a otros.",
  "Mantén un registro de tu progreso a lo largo del tiempo.",
  "Aprende a manejar la ansiedad antes de los exámenes.",
  "Encuentra momentos para reflexionar sobre tus logros.",
  "Diversifica tus métodos de estudio para mantenerlo interesante.",
  "Crea un ambiente de estudio inspirador con elementos visuales.",
  "Sé consciente de tus patrones de distracción y trabaja en super",
];

export const EMOTIONS = [
  {
    name: "Triste",
    value: "triste",
    color: "#1E88E5",
  },
  {
    name: "Enojado",
    value: "enojado",
    color: "#F44336",
  },
  {
    name: "Feliz",
    value: "feliz",
    color: "#4CAF50",
  },
  {
    name: "Cansado",
    value: "cansado",
    color: "#FFC107",
  },
  {
    name: "Ansioso",
    value: "ansioso",
    color: "#FF5722",
  },
];
